server.port=8080
telemetry.collector.kafka.producer.bootstrap.servers=localhost:9092
telemetry.collector.kafka.producer.topic.hub-events=telemetry.hubs.v1
telemetry.collector.kafka.producer.topic.sensor-events=telemetry.sensors.v1
grpc.server.port=59091