telemetry:
  aggregator:
    kafka:
      bootstrap-servers: localhost:9092
      consumer:
        group-id: aggregator
        topic:
          sensors: telemetry.sensors.v1
          snapshots: telemetry.snapshots.v1