telemetry.aggregator.kafka.bootstrap-servers=localhost:9092
telemetry.aggregator.kafka.consumer.group-id=aggregator
telemetry.aggregator.kafka.consumer.topic.sensors=telemetry.sensors.v1
telemetry.aggregator.kafka.consumer.topic.snapshots=telemetry.snapshots.v1
