spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/analyzer
    driverClassName: org.postgresql.Driver
    username: analyzer
    password: analyzer

grpc:
  client:
    hub-router:
      address: 'static://localhost:59090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

telemetry:
  analyzer:
    kafka:
      bootstrap-servers: 'localhost:9092'
      consumer:
        hub-events:
          group: 'group.hub-events'
          topic: 'telemetry.hubs.v1'
        snapshots:
          group: 'group.snapshots'
          topic: 'telemetry.snapshots.v1'
