server:
  port: 8080

telemetry:
  collector:
    kafka:
      producer:
        bootstrap:
          servers: localhost:9092
        topic:
          hub-events: telemetry.hubs.v1
          sensor-events: telemetry.sensors.v1

grpc:
  server:
    port: 59091